/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeProviderRouteImport } from './routes/become-provider'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TripRouteImport } from './routes/trip'
import { Route as TripPlannerRouteImport } from './routes/trip-planner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as ProviderRegisterRouteImport } from './routes/provider.register'
import { Route as ServicesIdRouteImport } from './routes/services.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeProviderRoute = BecomeProviderRouteImport.update({
  id: '/become-provider',
  path: '/become-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const TripPlannerRoute = TripPlannerRouteImport.update({
  id: '/trip-planner',
  path: '/trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProviderRegisterRoute = ProviderRegisterRouteImport.update({
  id: '/provider/register',
  path: '/provider/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-provider': typeof BecomeProviderRoute
  '/discover': typeof DiscoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trip': typeof TripRoute
  '/trip-planner': typeof TripPlannerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/provider/register': typeof ProviderRegisterRoute
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-provider': typeof BecomeProviderRoute
  '/discover': typeof DiscoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trip': typeof TripRoute
  '/trip-planner': typeof TripPlannerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/provider/register': typeof ProviderRegisterRoute
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-provider': typeof BecomeProviderRoute
  '/discover': typeof DiscoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trip': typeof TripRoute
  '/trip-planner': typeof TripPlannerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/provider/register': typeof ProviderRegisterRoute
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-provider'
    | '/discover'
    | '/reset-password'
    | '/trip'
    | '/trip-planner'
    | '/admin'
    | '/dashboard'
    | '/provider'
    | '/provider/register'
    | '/services/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-provider'
    | '/discover'
    | '/reset-password'
    | '/trip'
    | '/trip-planner'
    | '/admin'
    | '/dashboard'
    | '/provider'
    | '/provider/register'
    | '/services/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-provider'
    | '/discover'
    | '/reset-password'
    | '/trip'
    | '/trip-planner'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/provider'
    | '/provider/register'
    | '/services/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeProviderRoute: typeof BecomeProviderRoute
  DiscoverRoute: typeof DiscoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TripRoute: typeof TripRoute
  TripPlannerRoute: typeof TripPlannerRoute
  ProviderRegisterRoute: typeof ProviderRegisterRoute
  ServicesIdRoute: typeof ServicesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-provider': {
      id: '/become-provider'
      path: '/become-provider'
      fullPath: '/become-provider'
      preLoaderRoute: typeof BecomeProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-planner': {
      id: '/trip-planner'
      path: '/trip-planner'
      fullPath: '/trip-planner'
      preLoaderRoute: typeof TripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/provider/register': {
      id: '/provider/register'
      path: '/provider/register'
      fullPath: '/provider/register'
      preLoaderRoute: typeof ProviderRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeProviderRoute: BecomeProviderRoute,
  DiscoverRoute: DiscoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TripRoute: TripRoute,
  TripPlannerRoute: TripPlannerRoute,
  ProviderRegisterRoute: ProviderRegisterRoute,
  ServicesIdRoute: ServicesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
